### PR TITLE
CMake build system

### PR DESCRIPTION
**Pull request by mahrud**
This PR will track work on build scripts for CMake. I decided to build on top of this branch to avoid headache in the future.

The first two commits simplify or remove a few files in d/.
The second two commits add CMakeLists.txt files for the main folders necessary for building M2-binary.

Currently this doesn't build independently. Rather, following @mikestillman's starting file, some files (particularly headers) are bootstrapped from a folder built using Make. I also still need to improve inline comments.

To try it:
1. build M2 from this branch using usual Makefiles
2. edit the `${BOOTSTRAP}` parameter in `M2/CMakeLists.txt` to a finished local build
3. go to a build directory, say, `M2/BUILD/mahrud/build-cmake`
4. run `cmake ../../..`
5. run `make`

### CODE REVIEW

**Comment by mahrud** [comment]
One more thing: even though M2-binary compiles, it doesn't properly run yet. The error is this:
```
[mahrud@noether bin]$ ./M2-binary 
../../../../../Macaulay2/d/startup.m2.in:12:4:(0): error: symbol 'any' has not been defined as a function
../../../../../Macaulay2/d/startup.m2.in:12:4:(0): --entering debugger (type help to see debugger commands)
^C
^C

../../../../../Macaulay2/d/startup.m2.in:89:54:(0): error: expected method to be a function or TYPE => function'
../../../../../Macaulay2/d/startup.m2.in:89:54:(0): --entering debugger (type help to see debugger commands)
../../../../../Macaulay2/d/startup.m2.in:61:117:(0):[1]: error: symbol 'simpleToString' has not been defined as a function

<--bad prompt--> : 
../../../../../Macaulay2/d/startup.m2.in:354:36:(0):[2]: error: expected pair to have a method for '_'
../../../../../Macaulay2/d/startup.m2.in:354:36:(0):[2]: --entering debugger (type help to see debugger commands)
../../../../../Macaulay2/d/startup.m2.in:61:117:(0):[1]: error: symbol 'simpleToString' has not been defined as a function

<--bad prompt--> : 
```
I suspect there's a problem with building the correct `build-cmake/Macaulay2/d/startup.c` file, which is currently basically a hack.

**Comment by mahrud** [comment]
@DanGrayson Have you seen an error like the one above before? It seems like M2-binary doesn't recognize compiled functions?

Also, when does the `${exec_prefix}` from startup.c get translated?

**Comment by mikestillman** [comment]
Mahrud, great!  I'll try this out.

A question: how do you prefer I make new commits to 'eigen'?  (I have one to check in now).  I suppose  I check in to antonleykin:eigen directly (and then merge your branch in to that to test it)

Maybe we should also (try to) up the c++ version to c++14 or c++17?  It would be nice to be able to use features in these versions.

**Comment by mahrud** [comment]
Sure! I believe you have push access to my repository.

I think the commit I just pushed fixed that issue, so pull again before pushing.

I'm building with c++14 now and then 17.

**Comment by DanGrayson** [comment]
> @DanGrayson Have you seen an error like the one above before? It seems like M2-binary doesn't recognize compiled functions?

I bet the function actors4__prepare() didn't get run.


> 
> Also, when does the `${exec_prefix}` from startup.c get translated?

The code for doing that is in startup.c.

**Comment by mahrud** [comment]
The executable now works! (Though I only added the minimum necessary packages for now)

For reasons that I still don't understand, I can't make the binary look for the core files in `usr-dist/common/share/Macaulay2/Core`, but instead it is looking in `Macaulay2/share/Macaulay2/Core`, which sounds funny. I might be missing an easy config somewhere though, perhaps a cmake install directory prefix?

On that note, it would be great if we could simplify the directory structure a little bit.

**Comment by mikestillman** [comment]
For simplification of directory structure, do you mean the structure in `usr-host` and `usr-dist`, or the source directory structure?

**Comment by mikestillman** [comment]
After pulling, I get the following error on building on mac:
```
Scanning dependencies of target e-includes
[ 26%] Generating geores.hpp, geogbvec.hpp, statuscodes.h
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
make[2]: *** [Macaulay2/e-includes/geores.hpp] Error 1
make[2]: *** Deleting file `Macaulay2/e-includes/geores.hpp'
make[1]: *** [Macaulay2/e-includes/CMakeFiles/e-includes.dir/all] Error 2
```

**Comment by mahrud** [comment]
Ah, `sed` is different across platforms?? Try changing `sed -re` on the
last command in `e-includes/CMakeLists.txt" to just `sed -e`.

I need to take a look at some examples to see how they make CMake cross
platform without adding complexity.

**Comment by mikestillman** [comment]
The mac uses freebsd utilities, which are not (generally, in my opinion) as good as the gnu versions.  The same problem would happen on any bsd system, I expect.

**Comment by mahrud** [comment]
Closing this because the new branch name is `feature/cmake`, see [here](https://github.com/mahrud/M2/tree/feature/cmake).

**Pull request closed without merging**
