### PR TITLE
put -lgccpp back in

### PR DESCRIPTION
**Pull request by dimpase**

### CODE REVIEW

**Comment by DanGrayson** [comment]
In the documentation for gc we see this:
```
Linking against `libgccpp` in addition to the `gc` library overrides `::new`
(and friends) to allocate traceable memory but uncollectible memory, making
it safe to refer to collectible objects from the resulting memory.
```
The reason we took that out was to prevent overriding `operator new`, which we don't want to do.

PS: Using nm and a handy web demangler to extract the symbols from the library shows that these are included:
```
libgccpp.1.dylib: 0000000000000df0 T _operator delete[](void*)
libgccpp.1.dylib: 0000000000000d60 T _operator delete(void*)
libgccpp.1.dylib: 0000000000000d90 T _operator new[](unsigned long)
libgccpp.1.dylib: 0000000000000d00 T _operator new(unsigned long)
```
That's what we don't want.

**Comment by dimpase** [comment]
So? Yes, one has several implementations of `operator new[]` etc potentially available, but this is C++, and so the linker will pick up the correct one, as documented: 
  - if you derive from `gc` class, it will be the one in `libgccpp`, 
  - else it will be the standard C++ one.

If this is not the case, then it's a reportable GC bug, as it would not be contrary to the documented behaviour.

**Comment by dimpase** [comment]
by the way, after increasing `unlimit -m` and `-v`, and removing `packages/Macaulay2Doc/functions/roots-doc.m2` (as the `roots` computation using Pari segfaults), the build went as far as `tests/ComputationsBook/completeIntersections` - where it stopped due to some discrepancies in the output I didn't look at yet.

So it appears that a large part of M2 just works with these changes.

**Comment by dimpase** [comment]
In fact, save the `packages/Macaulay2Doc/functions/roots-doc.m2`, everything (modulo increased unlimits) completes, I just was confused by messages
```
if ! diff -B -b -u test.out.expected.trim test.out.trim ;\
then echo 'make[3]: *''** test failed: [Macaulay2/tests/ComputationsBook/.]' ;\
     false ;\
```
taking them for errors :-)

So yes, I maintain that with this patch we basically have a functioning build (apart from Pari interface).

**Comment by mikestillman** [comment]
Actually, I thought that pari was one reason we removed the gccpp library?

If we add in MPsolve, and with flint doing prime factorization pretty well (from what I have heard, at least), we could avoid using pari.  But we should be able to work fine with it too, I thought.

**Comment by dimpase** [comment]
It seems arb is a very natural choice (we use arb quite a bit in Sage) for univariate root finding:
http://arblib.org/#polynomials-and-power-series
it uses flint as the backend, and is well-adjusted to it.

**Comment by DanGrayson** [comment]
I think you must have intended your comment about `arb` to go somewhere else.

**Comment by DanGrayson** [comment]
Re: "the linker will pick up the correct one"

No, that's if you don't link with libgccpp.

**Comment by dimpase** [comment]
> No, that's if you don't link with libgccpp.

if that was correct then how would you think the mechanics of selecting the right interpretation of `::new` documented in `gp_cpp.h` is supposed to work?

**Comment by DanGrayson** [comment]
Could you point to a sentence in that file that contradicts something I said?

> > No, that's if you don't link with libgccpp.
> 
> if that was correct then how would you think the mechanics of selecting the right interpretation of `::new` documented in `gp_cpp.h` is supposed to work?
> 
> Note that in the same module one may have `::new (GC)` and `::new (NoGC)` - this would have been impossible to achieve if the crude way to link, or not, with libgccpp was the only way to control the behaviour of `::new`.

**Comment by dimpase** [comment]
I think you are saying that if you link with `libgccpp` then `::new` will always come from there and produce a GC-collectable instance whenever `::new` is invoked.
But `gp_cpp.h` explains in which cases it will happen, and in which cases it won't.
 (Maybe I misunderstand what you say).

I think that the semantic of the code does not change whether or not you link with `libgccpp`.
(the new GC does however need this linking in more cases than the old one).

**Comment by DanGrayson** [comment]
> I think you are saying that if you link with `libgccpp` then `::new` will always come from there and produce a GC-collectable instance whenever `::new` is invoked.

Half right: Then ::new will come from gc, but will be uncollectable.

> But `gp_cpp.h` explains in which cases it will happen, and in which cases it won't.
> (Maybe I misunderstand what you say).
> 
> I think that the semantic of the code does not change whether or not you link with `libgccpp`.
> (the new GC does however need this linking in more cases than the old one).

Yes, the semantics doesn't change, but still, we don't want libgc allocating the memory for ::new.  Why do we want that?  It's a personal preference, based on wanting to *know* when we need memory to be handled by libgc, and then arranging for it to happen explicitly.

**Comment by dimpase** [comment]
I don't see why all the `::new` will come from gc. There are plenty of `::new` defined in `libstdc++` (or `libc++`), and one of these is always linked with, for more type signatures than in `libgccpp`. E.g. on Debian one would see 
```
0000000000093070 T operator new[](unsigned long)
0000000000093080 T operator new[](unsigned long, std::nothrow_t const&)
0000000000093140 T operator new[](unsigned long, std::align_val_t)
0000000000093150 T operator new[](unsigned long, std::align_val_t, std::nothrow_t const&)
```
in  `libstdc++` , but only
```
0000000000001190 T operator new[](unsigned long)
```
in `libgccpp`. Thus e.g. `operator new[](unsigned long, std::nothrow_t const&)` won't come from the latter, as it's just not there!

**Comment by dimpase** [comment]
by the way, in `M2-binary` I see
```
U operator new(unsigned long, std::nothrow_t const&)
```
but there is no function with this signature in `libgccpp`, so it will come from `lib(std)c++`.

**Comment by DanGrayson** [comment]
> I don't see why all the `::new` will come from gc. 

Okay, but we don't want any of them coming from gc.

**Comment by dimpase** [comment]
the `::new` for instances of classes derived from the `gc` class must come from gc.

If I understand correctly,`::new (NoGC)` translates into a `::new` which is simply not in `libgccpp`.

I don't know  for sure which `::new` is used for instances of classes not derived from the `gc` class, I'll ask for rectification. (I suspect that it's one not in in `libgccpp`, though).

**Comment by dimpase** [comment]
As a way forward, one can extract the implementation of `GC_throw_bad_alloc()` from https://github.com/ivmai/bdwgc/blob/master/gc_cpp.cc (just erase all the new/delete functions there)
and use the result  instead of `libgccpp`.

**Comment by DanGrayson** [comment]
We've had no problem linking, so I would prefer first to try to reproduce your problem and see what the best solution is myself.

**Comment by DanGrayson** [comment]
What OS and version were you trying to build under?

**Comment by dimpase** [comment]
you need gc 8.0.4 (or perhaps some recent verision of gc 7, see https://github.com/ivmai/bdwgc/issues/268 for details) to reproduce this (on Linux).
We saw this error on Ubuntu and on Gentoo.

I haven't tried on OSX, but I suppose you will have the same issue (you might need to `make clean` enough to see it...)

**Comment by DanGrayson** [comment]
What version of Ubuntu?  What commit number for M2?

**Comment by dimpase** [comment]
the commit immediately preceding this very branch,, i.e. `eigen` branch of this repo as of yesterday. And, oops, it was not Ubuntu, but @antonleykin 's RedHat machine

**Comment by antonleykin** [comment]
This is the RHEL --- btw Dan might have access to this machine. 
```
[aleykin3@math31081 Macaulay2]$ cat /etc/redhat-release                                                                        
Red Hat Enterprise Linux Server release 7.6 (Maipo) 
```

**Comment by dimpase** [comment]
I also see these linking errors on `eigen` branch on Debian 10 (Buster), where I let M2 build its own gc (8.0.4) 
```
....
-o "/home/dimpase/work/M2/M2/usr-dist/x86_64-Linux-Debian-10/bin/M2-binary".tmp
/usr/bin/ld: ../e/mutablecomplex.o: in function `rawMutableComplex':
/home/dimpase/work/M2/M2/usr-host/include/gc/gc_cpp.h:410: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: ../e/localring.o: in function `LocalRing::create(PolyRing const*, GBComputation*)':
/home/dimpase/work/M2/M2/usr-host/include/gc/gc_cpp.h:410: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: ../e/GF.o: in function `GF::create(RingElement const*)':
/home/dimpase/work/M2/M2/usr-host/include/gc/gc_cpp.h:410: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: ../e/ZZp.o: in function `Z_mod::create(int)':
/home/dimpase/work/M2/M2/usr-host/include/gc/gc_cpp.h:410: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: ../e/schurSn.o: in function `SchurSnRing::create(Ring const*, int)':
/home/dimpase/work/M2/M2/usr-host/include/gc/gc_cpp.h:410: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: ../e/schur2.o:/home/dimpase/work/M2/M2/usr-host/include/gc/gc_cpp.h:410: more undefined references to `GC_throw_bad_alloc()' follow
...
```

**Comment by DanGrayson** [comment]
@antonleykin -- I can't compile on your machine math31081, because /tmp is full.  (Use "df /tmp" to verify.)

**Comment by DanGrayson** [comment]
Okay, I've started a Debian 10 build on anton's eigen branch at commit e93c50913ed6fc29c0d6cbafa17d9a2fc3ae4263

**Comment by antonleykin** [comment]
> @antonleykin -- I can't compile on your machine math31081, because /tmp is full. (Use "df /tmp" to verify.)

@DanGrayson -- that's right: there were lots of M2 temporary files :)
Now it is emptier.

**Comment by DanGrayson** [comment]
> Okay, I've started a Debian 10 build on anton's eigen branch at commit [e93c509](https://github.com/antonleykin/M2/commit/e93c50913ed6fc29c0d6cbafa17d9a2fc3ae4263)

The build compiled with no undefined symbols.  I can't reproduce your problem.

Well, you did say "you need gc 8.0.4".  Did you install that yourself for some reason?  (The gc that comes with Debian 10 is 7.6.4.)  Or did you tell our configure script to build it?

**Comment by DanGrayson** [comment]
> > @antonleykin -- I can't compile on your machine math31081, because /tmp is full. (Use "df /tmp" to verify.)
> 
> @DanGrayson -- that's right: there were lots of M2 temporary files :)
> Now it is emptier.

Thanks.

Did you install eigen3 just for yourself?  Or should it be visible to me somewhere?

**Comment by antonleykin** [comment]
> Did you install eigen3 just for yourself? Or should it be visible to me somewhere?
It is not visible --- I have no admin rights there.

**Comment by dimpase** [comment]
> Well, you did say "you need gc 8.0.4". Did you install that yourself for some reason? (The gc that comes with Debian 10 is 7.6.4.) Or did you tell our configure script to build it?

yes, I did tell M2 to install it, as this is what VERSION in libraries/gc/Makefile.in is saying, 8.0.4, right?

I think that  for gc 7 you need a newer than 7.6.4 gc, 7.6.8+ accoring to the gc maintainer.

And indeed with 8.0.4, and M2 built from scratch, I do get the error in question.

**Comment by dimpase** [comment]
> As a way forward, one can extract the implementation of `GC_throw_bad_alloc()` from https://github.com/ivmai/bdwgc/blob/master/gc_cpp.cc (just erase all the new/delete functions there)
> and use the result instead of `libgccpp`.

I've implemented this in https://github.com/antonleykin/M2/pull/6

**Comment by DanGrayson** [comment]
A better fix than #6 or the current proposal is displayed at https://github.com/antonleykin/M2/pull/6#issuecomment-540205866

**Comment by dimpase** [comment]
ok, we can close this and proceed with #6

**Comment by ivmai** [comment]
> As a way forward, one can extract the implementation of `GC_throw_bad_alloc()` from https://github.com/ivmai/bdwgc/blob/master/gc_cpp.cc (just erase all the new/delete functions there)
> and use the result instead of `libgccpp`.

Now I understand the issue. I will address in bdwgc, although I don't see a good way to do it right now.

**Comment by ivmai** [comment]
Still working on it. As a temporal workaround you could use -D GC_INCLUDE_NEW (or -D GC_NEW_ABORTS_ON_OOM) when building the code that uses gc_cpp.h.

**Comment by DanGrayson** [comment]
Thanks.  (The latter is the one I proposed at https://github.com/antonleykin/M2/pull/6#issuecomment-540205866 ).

**Comment by ivmai** [comment]
I've fixed this in bdgwc upstream (see commits https://github.com/ivmai/bdwgc/commit/803f7ed4bb and https://github.com/ivmai/bdwgc/commit/3efd0bc4e443132653d42aca1a80b22b14930dd8) - https://github.com/ivmai/bdwgc/issues/268.
Portable clients should use -lgctba .
But as a workaround, as it was mentioned above, there are 3 variants (w/o application of the 2 mentioned commits):
- define GC_throw_bad_alloc() somewhere in your code
- define GC_NEW_ABORTS_ON_OOM macro before include gc_cpp.h (this will cause abort on out-of-memory)
- define GC_INCLUDE_NEW macro before include gc_cpp.h (this is not portable, may not compile or work as expected on some targets)

**Pull request closed without merging**
